version: '3'

services:
  # Game server
  gsserver:
    image: ${HUB_ALIYUN}gs_server:latest
    container_name: gsserver
    volumes:
      - "${SHARED_DIR}/:/home"
      # - "${SHARED_DIR}/billing/:/home/billing/"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: ${RESTART}
    links:
      - gsmysql:gsmysql
      - gsnginx:gsnginx
      - gsphp:gsphp
      - gsredis:gsredis
  # Database
  gsmysql:
    image: ${HUB_ALIYUN}gs_mysql:latest
    container_name: gsmysql
    volumes:
      - "${SHARED_DIR}/gsmysql/:/var/lib/mysql"
    ports:
      - "${TL_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${TL_MYSQL_PASSWORD}
      MYSQL_DATABASE: "tlbbdb"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: ${RESTART}
  # WEBSERVER
  gsnginx:
    image: ${HUB_ALIYUN}gs_nginx:latest
    container_name: gsnginx
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    volumes:
      - ${SHARED_DIR}/www/:/www/:rw
      - ${SHARED_DIR}/ssl/:/ssl:rw # 如果有ssl证书，请放在此目录里面
      - ${SHARED_DIR}/conf.d/:/etc/nginx/conf.d/:rw #新增网站，需要将配置放在此目录
      - ${SHARED_DIR}/log/nginx/:/var/log/nginx/:rw
    environment:
      TZ: "$TZ"
    restart: always
  # PHP
  gsphp:
    image: ${HUB_ALIYUN}gs_php:latest
    container_name: gsphp
    volumes:
      - ${SHARED_DIR}/www/:/www/:rw
      - ${SHARED_DIR}/log/php/:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
  # NOSQL
  gsredis:
    image: ${HUB_ALIYUN}gs_redis:latest
    container_name: gsredis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${SHARED_DIR}/redis:/data/:rw
    restart: always
    environment:
      TZ: "$TZ"
