FROM registry.cn-hangzhou.aliyuncs.com/yulinzhihou/gs_redis:v2.0.0

# FROM redis:5.0.12

# LABEL author="yulinzhihou@gmail.com" website="https://gsgameshare.com"

# COPY ./redis.conf /etc/

# ENTRYPOINT ["redis-server", "/etc/redis.conf"]