FROM registry.cn-hangzhou.aliyuncs.com/yulinzhihou/gs_nginx:v2.0.1

# FROM nginx:1.21.0-alpine

# LABEL author="yulinzhihou" website="https://gsgameshare.com"

# COPY ./conf.d/*.conf /etc/nginx/conf.d/*.conf
# COPY ./fastcgi_params /etc/nginx/fastcgi_params
# COPY ./fastcgi-php.conf /etc/nginx/fastcgi-php.conf
# COPY ./nginx.conf /etc/nginx/nginx.conf

# RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories;

# WORKDIR /home/www
